// src/client/react/app.js
import React, { Component } from 'react';
import { render } from 'react-dom';

import request from 'superagent';

import MyInput from './components/MyInput';

class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			people: []
		}
	}
	componentWillMount() {
		request.get('data.json')
			.end((err, res) => {
				this.setState({
					people: res.body
				});
			});
	}
	render() {
		const { people } = this.state;
		return (
			<div className="container">
				<h1>React</h1>
				<table>
					<thead>
						<tr>
							<th>Code</th>
							<th>Name</th>
						</tr>
					</thead>
					<tbody>
					{people.map((item, key) =>
						<tr key={ key }>
							<td className="item-code"><MyInput type="number" value={ item.code } /></td>
							<td className="item-name"><MyInput type="string" value={ item.name } /></td>
						</tr>
					)}
					</tbody>
				</table>
			</div>
		);
	}
}

render(<App />, document.querySelector('#app'));

// src/client/vue/components/App.vue
<template>
	<div class="container">
		<h1>Vue</h1>
		<table>
			<thead>
				<tr>
					<th>Code</th>
					<th>Name</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="item in people">
					<td class="item-code"><my-input type="number" :defaultvalue="item.code" /></td>
					<td class="item-name"><my-input type="string" :defaultvalue="item.name" /></td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<script>
	import request from 'superagent';
	import MyInput from './MyInput';

	export default {
		data() {
			return {
				people: []
			}
		},
		components: { 'my-input': MyInput },
		beforeCreate() {
			request.get('data.json', (err, res) => {
				this.people = res.body;
			});
		}
	}
</script>
